### ISSUE TITLE
Use junctions in windows

### ISSUE THREAD

**Issue by amosyuen** [iguntur/make-symlinks#1]
Windows needs admin privileges to create symlinks, but not junctions.

**Comment by amosyuen** [comment]
More info https://github.com/gulpjs/vinyl-fs/issues/210

**Comment by iguntur** [comment]
Honestly,  I don't use windows for now.

Are you want to handle it?

**Thank you.**

**Comment by amosyuen** [comment]
Created pull request https://github.com/iguntur/make-symlinks/pull/2
